// src/components/schedule/ScheduleHeader.vue
<template>
  <div class="flex items-center justify-between mb-6">
    <div class="flex items-center gap-4">
      <select class="bg-fitness-card text-fitness-text border border-fitness-muted rounded-md px-4 py-2">
        <option>CrossFit</option>
        <option>Personal Training</option>
        <option>Yoga</option>
      </select>
      <button class="px-4 py-2 bg-fitness-muted text-fitness-text rounded-md">
        Post Schedule
      </button>
    </div>
    
    <div class="flex items-center gap-4">
      <div class="flex items-center gap-2 bg-fitness-card px-4 py-2 rounded-md">
        <ChevronLeft class="w-5 h-5 text-fitness-text cursor-pointer" />
        <span class="text-fitness-text">Week of May 29th 2023</span>
        <ChevronRight class="w-5 h-5 text-fitness-text cursor-pointer" />
      </div>
      <button class="px-4 py-2 bg-fitness-muted text-fitness-text rounded-md">
        Clone Week
      </button>
    </div>
    
    <button class="px-4 py-2 bg-fitness-accent text-white rounded-md">
      Clock-In
    </button>
  </div>
</template>

<script setup lang="ts">
import { ChevronLeft, ChevronRight } from 'lucide-vue-next'
</script>

// src/components/schedule/ScheduleHeader.tsx
import { ChevronLeft, ChevronRight } from "lucide-react";

const ScheduleHeader = () => {
  return (
    <div className="flex items-center justify-between mb-6">
      <div className="flex items-center gap-4">
        <select className="bg-fitness-card text-fitness-text border border-fitness-muted rounded-md px-4 py-2">
          <option>CrossFit</option>
          <option>Personal Training</option>
          <option>Yoga</option>
        </select>
        <button className="px-4 py-2 bg-fitness-muted text-fitness-text rounded-md">
          Post Schedule
        </button>
      </div>
      
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2 bg-fitness-card px-4 py-2 rounded-md">
          <ChevronLeft className="w-5 h-5 text-fitness-text cursor-pointer" />
          <span className="text-fitness-text">Week of May 29th 2023</span>
          <ChevronRight className="w-5 h-5 text-fitness-text cursor-pointer" />
        </div>
        <button className="px-4 py-2 bg-fitness-muted text-fitness-text rounded-md">
          Clone Week
        </button>
      </div>
      
      <button className="px-4 py-2 bg-fitness-accent text-white rounded-md">
        Clock-In
      </button>
    </div>
  );
};

export default ScheduleHeader;
