// src/components/layout/Header.vue
<template>
  <header class="flex items-center justify-between px-6 py-4 bg-fitness-card border-b border-fitness-muted">
    <nav class="flex gap-4">
      <button class="px-4 py-2 rounded-md bg-[#15e7fb] text-white">Schedule</button>
      <button class="px-4 py-2 rounded-md hover:bg-fitness-muted text-fitness-text">Hrs/ Payroll</button>
      <button class="px-4 py-2 rounded-md hover:bg-fitness-muted text-fitness-text">Reports</button>
      <router-link 
        to="/settings" 
        class="px-4 py-2 rounded-md hover:bg-fitness-muted text-fitness-text flex items-center gap-2"
      >
        <Settings class="w-4 h-4" />
        Settings
      </router-link>
    </nav>
    <div class="flex items-center gap-6">
      <Sun class="w-5 h-5 text-fitness-text cursor-pointer" />
      <div class="flex items-center gap-4">
        <span class="text-fitness-text">Messages</span>
        <MessageSquare class="w-5 h-5 text-fitness-text" />
      </div>
      <Bell class="w-5 h-5 text-fitness-text" />
      <div class="flex items-center gap-2">
        <div class="w-8 h-8 bg-[#15e7fb] rounded-full flex items-center justify-center text-white font-semibold">
          HG
        </div>
        <span class="text-fitness-text">Heath Graham</span>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
import { Settings, Sun, MessageSquare, Bell } from 'lucide-vue-next'
</script>

// src/components/layout/Header.tsx
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { LogOut } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useNavigate } from "react-router-dom";

const Header = () => {
  const navigate = useNavigate();

  const handleLogout = async () => {
    await supabase.auth.signOut();
    navigate("/login");
  };

  return (
    <header className="bg-fitness-card border-b border-fitness-border">
      <div className="container mx-auto px-4 py-4">
        <div className="flex justify-between items-center">
          <Link to="/" className="text-fitness-text text-xl font-bold font-['Cousine'] tracking-wider">
            ScheduleFor
          </Link>
          <div className="flex items-center gap-4">
            <Link to="/">
              <Button variant="ghost">Schedule</Button>
            </Link>
            <Link to="/staff">
              <Button variant="ghost">Staff</Button>
            </Link>
            <Link to="/payroll">
              <Button variant="ghost">Payroll/Hrs</Button>
            </Link>
            <Link to="/reports">
              <Button variant="ghost">Reports</Button>
            </Link>
            <Link to="/settings">
              <Button variant="ghost">Settings</Button>
            </Link>
            <Button variant="ghost" size="icon" onClick={handleLogout}>
              <LogOut className="h-5 w-5 text-fitness-text" />
            </Button>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
